BACKUP_MOUNT_FOLDER='/mnt/'
DEVICE_MOUNT_FOLDER='/mount/'
DEVICE_FOLDER='/dev/'
BACKUP_PARTITION_ALIAS='backup'

BACKUP_CONF_FILE='/opt/ds/backup.conf'
DEVICES_CONF_FILE='/opt/ds/sync.conf'

LOG=1
LOG_FOLDER='/tmp/ds/'
LOG_FILE='log'
LOG_PREFIX='log_'

HASHFUNC='sha1sum'
FOLDER_DIGITS=4
MAX_WAITING_TIME=10

STATUS_LED=1
STATUS_LED_PIN=8
STATUS_LED_FREQ=2 #Hz

BACKUP_CONNECTED_LED=1
BACKUP_CONNECTED_LED_PIN=7

FORMAT_SRC_DEVICE=0
